
server:
  port: 8081

spring:
  application:
    name: 'fornecedor'
  datasource:
    password: 
    username: 
    url: jdbc:postgresql://localhost:5433/fornecedor
  jpa:
    hibernate:
      ddl-auto: validate
   
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka