
spring:
  application:
    name: 'fornecedor'
  profiles:
    active: default
  config:
    import: configserver:http://localhost:8888
      
server:
  port: 8081
   
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka